"""Обновил Чаты

Revision ID: 0751cccc4532
Revises: 51e479873898
Create Date: 2020-05-09 00:08:14.174526

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0751cccc4532'
down_revision = '51e479873898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.alter_column('chats', 'status',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=True)
    # op.drop_column('messages', 'with_attachments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    op.alter_column('chats', 'status',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
