"""Снова обновил фотки

Revision ID: 09d9b76ac9b8
Revises: 50f3f53ff9aa
Create Date: 2020-07-04 01:58:17.415665

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '09d9b76ac9b8'
down_revision = '50f3f53ff9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_constraint(None, 'achievements', type_='foreignkey')
    # op.drop_column('achievements', 'photo_id')
    # op.drop_constraint(None, 'apps', type_='foreignkey')
    # op.drop_column('apps', 'photo_id')
    # op.drop_constraint(None, 'chats', type_='foreignkey')
    # op.drop_column('chats', 'photo_id')
    # op.drop_column('messages', 'with_attachments')
    # op.drop_constraint(None, 'music', type_='foreignkey')
    # op.drop_column('music', 'photo_id')
    # op.add_column('photo_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # op.alter_column('photo_association', 'photo_id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=True)
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.drop_column('posts', 'photo_id')
    # op.drop_column('posts', 'user_id')
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_column('users', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'photos', ['photo_id'], ['id'])
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('posts', sa.Column('photo_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'photos', ['photo_id'], ['id'])
    op.alter_column('photo_association', 'photo_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_column('photo_association', 'id')
    op.add_column('music', sa.Column('photo_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'music', 'photos', ['photo_id'], ['id'])
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    op.add_column('chats', sa.Column('photo_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'chats', 'photos', ['photo_id'], ['id'])
    op.add_column('apps', sa.Column('photo_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'apps', 'photos', ['photo_id'], ['id'])
    op.add_column('achievements', sa.Column('photo_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'achievements', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
