"""Добавил Post

Revision ID: 0fd725ce25a0
Revises: b59d93798eb5
Create Date: 2020-04-04 18:50:58.923423

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0fd725ce25a0'
down_revision = 'b59d93798eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
