"""Что-то ещё добавил2

Revision ID: 111816e24f20
Revises: 9558b731f0e0
Create Date: 2020-04-05 00:18:07.541473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111816e24f20'
down_revision = '9558b731f0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('posts')
    # ### end Alembic commands ###
