"""Обновил посты

Revision ID: 286bb1aa0a69
Revises: 659f6f296a3e
Create Date: 2020-05-26 00:38:28.089152

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '286bb1aa0a69'
down_revision = '659f6f296a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('angry_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('disappointed_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('heart_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('laughter_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('like_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('modified_date', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('screaming_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('smile_emoji_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('smile_with_heart_eyes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'smile_with_heart_eyes_count')
    op.drop_column('posts', 'smile_emoji_count')
    op.drop_column('posts', 'screaming_emoji_count')
    op.drop_column('posts', 'modified_date')
    op.drop_column('posts', 'like_emoji_count')
    op.drop_column('posts', 'laughter_emoji_count')
    op.drop_column('posts', 'heart_emoji_count')
    op.drop_column('posts', 'disappointed_emoji_count')
    op.drop_column('posts', 'angry_emoji_count')
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    op.create_table('achievement_association',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('achievement_id', sa.INTEGER(), nullable=False),
                    sa.Column('is_get', sa.BOOLEAN(), nullable=True),
                    sa.CheckConstraint('is_get IN (0, 1)'),
                    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
                    )
    op.create_table('app_association',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('app_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'app_id')
                    )
    # ### end Alembic commands ###
