"""Добавил токен

Revision ID: 3bf222aa8e56
Revises: 09d9b76ac9b8
Create Date: 2020-07-08 17:18:59.349757

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3bf222aa8e56'
down_revision = '09d9b76ac9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('messages', 'with_attachments')
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.drop_column('posts', 'user_id')
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_column('users', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'photos', ['photo_id'], ['id'])
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_column('users', 'token_expiration')
    op.drop_column('users', 'token')
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
