"""Update messages

Revision ID: 4972af705c63
Revises: b0652f75aba8
Create Date: 2020-03-19 20:24:19.639053

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4972af705c63'
down_revision = 'b0652f75aba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('with_attachments', sa.Boolean(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('user_to', sa.Integer(), nullable=True),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['user_to'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
