"""Update Apps

Revision ID: 51e479873898
Revises: d583fcee33f6
Create Date: 2020-05-04 17:29:39.022431

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51e479873898'
down_revision = 'd583fcee33f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
