"""Delete errors

Revision ID: 64e13ea1cba9
Revises: d426c1f07bb6
Create Date: 2020-03-19 22:27:16.226500

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '64e13ea1cba9'
down_revision = 'd426c1f07bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_to', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_to'], ['id'])
    # ### end Alembic commands ###
