"""Обновил пользователя

Revision ID: 659f6f296a3e
Revises: c5ea9c6550d9
Create Date: 2020-05-17 22:37:57.519628

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '659f6f296a3e'
down_revision = 'c5ea9c6550d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('app_association')
    # op.drop_table('achievement_association')
    # op.drop_column('messages', 'with_attachments')
    op.add_column('users', sa.Column('count_apps', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_chats', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_groups', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_incoming_messages', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_music', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_outgoing_messages', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_posts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_upload_photos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'count_upload_photos')
    op.drop_column('users', 'count_posts')
    op.drop_column('users', 'count_outgoing_messages')
    op.drop_column('users', 'count_music')
    op.drop_column('users', 'count_incoming_messages')
    op.drop_column('users', 'count_groups')
    op.drop_column('users', 'count_chats')
    op.drop_column('users', 'count_apps')
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    op.create_table('achievement_association',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('achievement_id', sa.INTEGER(), nullable=False),
                    sa.Column('is_get', sa.BOOLEAN(), nullable=True),
                    sa.CheckConstraint('is_get IN (0, 1)'),
                    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
                    )
    op.create_table('app_association',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('app_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'app_id')
                    )
    # ### end Alembic commands ###
