"""Добавил новые таблицы

Revision ID: 671998e9c66f
Revises: ea10c2d8b149
Create Date: 2020-03-11 23:34:05.872344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671998e9c66f'
down_revision = 'ea10c2d8b149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_of_chat', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('last_time_message', sa.DateTime(), nullable=False),
    sa.Column('last_message', sa.String(), nullable=False),
    sa.Column('count_new_messages', sa.Integer(), nullable=True),
    sa.Column('count_messages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_of_chat', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('last_time_message', sa.DateTime(), nullable=False),
    sa.Column('last_message', sa.String(), nullable=False),
    sa.Column('count_new_messages', sa.Integer(), nullable=True),
    sa.Column('count_messages', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('chats')
    op.drop_table('photos')
    # ### end Alembic commands ###
