"""Delete errors ver2

Revision ID: 88f017999104
Revises: 64e13ea1cba9
Create Date: 2020-03-19 22:31:44.695346

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '88f017999104'
down_revision = '64e13ea1cba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'to')
    # ### end Alembic commands ###
