"""Added People

Revision ID: 9f6821109f17
Revises: 111816e24f20
Create Date: 2020-04-10 21:15:07.725966

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9f6821109f17'
down_revision = '111816e24f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_table('people_association')
    op.drop_table('people')
    # ### end Alembic commands ###
