"""Обновил таблички и добавил комментарии

Revision ID: b59d93798eb5
Revises: 05d2dd5380cc
Create Date: 2020-04-04 18:13:06.778703

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b59d93798eb5'
down_revision = '05d2dd5380cc'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('chats', 'last_time_message',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('messages', 'with_attachments',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'with_attachments',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('chats', 'last_time_message',
                    existing_type=sa.DATETIME(),
                    nullable=True)
    # ### end Alembic commands ###
