"""Добавил приложения

Revision ID: c5ea9c6550d9
Revises: 0751cccc4532
Create Date: 2020-05-17 17:02:10.158461

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5ea9c6550d9'
down_revision = '0751cccc4532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_table('app_association')
    # op.drop_table('achievement_association')
    # op.drop_column('messages', 'with_attachments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    op.create_table('achievement_association',
                    sa.Column('user', sa.INTEGER(), nullable=True),
                    sa.Column('achievement', sa.INTEGER(), nullable=True),
                    sa.Column('is_get', sa.BOOLEAN(), nullable=True),
                    sa.CheckConstraint('is_get IN (0, 1)'),
                    sa.ForeignKeyConstraint(['achievement'], ['achievements.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], )
                    )
    op.create_table('app_association',
                    sa.Column('user', sa.INTEGER(), nullable=True),
                    sa.Column('app', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['app'], ['apps.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], )
                    )
    # ### end Alembic commands ###
