"""Update photos

Revision ID: d426c1f07bb6
Revises: 4972af705c63
Create Date: 2020-03-19 21:38:14.288470

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd426c1f07bb6'
down_revision = '4972af705c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('count_messages', sa.INTEGER(), nullable=True))
    op.add_column('photos', sa.Column('last_message', sa.VARCHAR(), nullable=False))
    op.add_column('photos', sa.Column('last_time_message', sa.DATETIME(), nullable=False))
    op.add_column('photos', sa.Column('count_new_messages', sa.INTEGER(), nullable=True))
    op.add_column('photos', sa.Column('type_of_chat', sa.INTEGER(), nullable=False))
    op.add_column('photos', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('photos', sa.Column('status', sa.INTEGER(), nullable=False))
    op.alter_column('photos', 'data',
                    existing_type=sa.BLOB(),
                    nullable=True)
    # ### end Alembic commands ###
