"""Обновил Post

Revision ID: da689d320e63
Revises: 0fd725ce25a0
Create Date: 2020-04-04 23:20:29.526023

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'da689d320e63'
down_revision = '0fd725ce25a0'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('posts')
    # op.drop_constraint(None, 'chats', type_='foreignkey')
    # op.drop_column('chats', 'user_id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
