"""Жёстко обновил посты

Revision ID: e4a5ee234ad9
Revises: 286bb1aa0a69
Create Date: 2020-05-26 02:51:12.064010

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e4a5ee234ad9'
down_revision = '286bb1aa0a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('with_attachments', sa.BOOLEAN(), nullable=True))
    op.create_table('app_association',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('app_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'app_id')
                    )
    op.create_table('achievement_association',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('achievement_id', sa.INTEGER(), nullable=False),
                    sa.Column('is_get', sa.BOOLEAN(), nullable=True),
                    sa.CheckConstraint('is_get IN (0, 1)'),
                    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
                    )
    # ### end Alembic commands ###
