"""Добавил чаты, фото и обновил юзеров

Revision ID: ea10c2d8b149
Revises: 9166445153c2
Create Date: 2020-03-11 23:29:35.891904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea10c2d8b149'
down_revision = '9166445153c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('can_see_audio', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_see_groups', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_see_videos', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_write_message', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('education', sa.String(), nullable=True))
    op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('in_black_list', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscriptions_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscriptions_count')
    op.drop_column('users', 'status')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'is_closed')
    op.drop_column('users', 'in_black_list')
    op.drop_column('users', 'followers_count')
    op.drop_column('users', 'education')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'can_write_message')
    op.drop_column('users', 'can_see_videos')
    op.drop_column('users', 'can_see_groups')
    op.drop_column('users', 'can_see_audio')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'age')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
