"""Added App, music, achievements

Revision ID: eeb1de3c7ce8
Revises: aaa215ee08c9
Create Date: 2020-04-16 20:33:45.912349

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eeb1de3c7ce8'
down_revision = 'aaa215ee08c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('achievements',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.Column('data', sa.BLOB(), nullable=False),
    # sa.Column('photo_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('apps',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.Column('secondary_text', sa.String(), nullable=False),
    # sa.Column('description', sa.String(), nullable=False),
    # sa.Column('photo_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('music',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.Column('author', sa.String(), nullable=False),
    # sa.Column('duration', sa.Integer(), nullable=False),
    # sa.Column('data', sa.BLOB(), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=True),
    # sa.Column('photo_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('achievement_association',
    # sa.Column('user', sa.Integer(), nullable=True),
    # sa.Column('achievement', sa.Integer(), nullable=True),
    # sa.Column('is_get', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['achievement'], ['achievements.id'], ),
    # sa.ForeignKeyConstraint(['user'], ['users.id'], )
    # )
    # op.create_table('app_association',
    # sa.Column('user', sa.Integer(), nullable=True),
    # sa.Column('app', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['app'], ['apps.id'], ),
    # sa.ForeignKeyConstraint(['user'], ['users.id'], )
    # )
    # op.create_table('music_association',
    # sa.Column('user', sa.Integer(), nullable=True),
    # sa.Column('music', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['music'], ['music.id'], ),
    # sa.ForeignKeyConstraint(['user'], ['users.id'], )
    # )
    # op.drop_table('photo_association')
    # op.alter_column('chats', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_table('photo_association',
                    sa.Column('user', sa.INTEGER(), nullable=True),
                    sa.Column('photo', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['photo'], ['photos.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], )
                    )
    op.drop_table('music_association')
    op.drop_table('app_association')
    op.drop_table('achievement_association')
    op.drop_table('music')
    op.drop_table('apps')
    op.drop_table('achievements')
    # ### end Alembic commands ###
